---
- hosts: all
  become: yes

  tasks:
    - name: Install packages
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - build-essential
        - git

    - name: Check if the git repository exists
      stat: path=/opt/yolo
      register: yolo_repo

    - name: Fetch the Github repository
      git:
        repo: https://github.com/smmuiruri/week_ip.git
        dest: /opt/yolo
      when: not yolo_repo.stat.exists      

    - include: tasks/mongodb.yml
    - include: tasks/client.yml
    - include:  tasks/backend.yml